name: "Push to master"
on: push
jobs:
  docs:
    # running only on master branch pushes
    if: ${{ github.ref_name == 'master' && github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - name: Generate documentation
        run: npm run docs
      - name: Commit updates
        if: ${{ success() }}
        run: |
          git config --global user.name "${{ github.actor }}" &&
          git config --global user.email "${{ github.actor }}@users.noreply.github.com" &&
          git add docs &&
          git commit -am "regenerated documentation at $( date -I'minutes' )"
          git push
          
