name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Update npm version to latest
        run: npm ci -g npm@latest # stop showing warnings about the lockfile
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: "Run build"
        run: npm run build
