name: "Publish"

# the workflow is only triggered on version tag pushes to the master branch
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
      - v*.*

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm test
            - if: ${{ success() }}
              run: |
                  npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}